### ISSUE TITLE
Error attempting to login

### ISSUE THREAD

**Issue by jeff-kingston** [pkillnine/audible-activator-robobrowser#1]
I ran this with python3. I did install RoboBrowser.  Did I miss something? Running on MacOS.

$ ./activator.py
Email address associated with Amazon account:XXXXX@XXXX.COM
Password:

Step 0: setup

Step 1: login to Audible

Traceback (most recent call last):
  File "./activator.py", line 118, in <module>
    account.fetch_activation_bytes()
  File "./activator.py", line 91, in fetch_activation_bytes
    self._login_and_authenticate()
  File "./activator.py", line 64, in _login_and_authenticate
    form = self.browser.get_form()
  File "/usr/local/lib/python3.6/site-packages/robobrowser/browser.py", line 293, in get_form
    form = self.find(_form_ptn, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/robobrowser/browser.py", line 144, in find
    return self.parsed.find
  File "/usr/local/lib/python3.6/site-packages/robobrowser/browser.py", line 138, in parsed
    return self.state.parsed
  File "/usr/local/lib/python3.6/site-packages/werkzeug/utils.py", line 73, in __get__
    value = self.func(obj)
  File "/usr/local/lib/python3.6/site-packages/robobrowser/browser.py", line 40, in parsed
    features=self.browser.parser,
  File "/usr/local/lib/python3.6/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by pkillnine** [comment]
Install the `lxml` library from pypi (not sure how this is done on MacOS, it's the same way as you installed robobrowser).

I'll update the documentation to make it a requirement. The cause of the error I think is [this line](https://github.com/pkillnine/audible-activator-robobrowser/blob/master/activator.py#L17) when not having the `lxml` package installed. I didn't put it as a requirement because I thought it came with Python.

**Comment by jeff-kingston** [comment]
Installed lxml and I am able to progress to a new error.  I will close this issue and open a new one.
